kind: Deployment
apiVersion: apps/v1
metadata:
  name: my
spec:
  replicas: 3
  selector:
    matchLabels:
      san: edw
  template:
    metadata:
      name: jos
      labels:
        san: edw
    spec:
      containers:
        - name: c1
          image: sanjay166/health:1
