kind: Deployment
apiVersion: apps/v1
metadata:
  name: my
spec:
  replicas: 3
  selector:
    matchLabels:
      luv: jos
  template:
    metadata:
      name: jos
      labels:
        luv: jos
    spec:
      containers:
        - name: c1
          image: sanjay166/health:1
